PointRule = {
    "A": 7,
    "A-": 6,
    "B+": 5,
    "B": 4,
    "B-": 3,
    "C": 2,
    "Cook_self": 8,
    "Cook_buyFood": 4,
    "Cook_buyEatery": 2,
    "Extra_DoneInWeek": 15,
    "Extra_DoneInWorkDays": 40,
    "DentalFloss":2,
    "---------":0,
    "sleepLate_20": -2,
    "sleepLate_40": -5,
    "sleepLate_60": -15,
    "less5H":-2,
    "less4H":-6,
    "less3H":-12,
    "Others": 0,
}
